### ISSUE TITLE
Review code to see if we need to do anything special for UTF8 support. 

### ISSUE THREAD

**Issue by DarkSide666** [atk4/dsql#110]
Check if we have any of these methods and if so,then use their mb_ equivalent.
http://php.net/manual/en/ref.mbstring.php

Also we need to add some test-scripts:
- [ ] is utf8 good as a value?
- [ ] is utf8 good when dumping queries (debug)
- [ ] is utf8 for field names?

**Comment by romaninsh** [comment]
if you find any, please point out. In most cases it's safe not to use mb_ which should work OK even with multi-byte strings.

**Comment by mvorisek** [comment]
@DarkSide666 Try to use some tool over all major repos and propose PRs and then close this.

**Comment by mvorisek** [comment]
we fully support UTF-8, if any issue will be found, open an issue for it
