### ISSUE TITLE
Add support for WITH clause

### ISSUE THREAD

**Issue by tasso85** [atk4/dsql#117]
Add support in the `Query` class to implement [https://en.wikipedia.org/wiki/Hierarchical_and_recursive_queries_in_SQL#Common_table_expression](CTE) using SQL `WITH` clause.

The signature of the function could be the following:

``` php
public function with($expr, $table_alias, $fields = [])
public function withRecursive($expr, $table_alias, $fields = [])
```

The alias in this case should be mandatory (single identifier or array), while expr could be any kind of subtable expression, or even a union. $fields is optional.

To produce the following query

``` sql
WITH RECURSIVE
  cnt(x) AS (VALUES(1) UNION ALL SELECT x+1 FROM cnt WHERE x<1000000)
SELECT x FROM cnt;
```

you would do:

``` php
$expr = newExpression('values(1) union all select x+1 from cnt where x<1000000');

$q = new Query();
$q->table('cnt');
$q->field('x');
$q->withRecursive($expr, 'cnt', ['x']);
```

It should be possible to execute with() multiple times.

**Comment by romaninsh** [comment]
http://guilhembichot.blogspot.co.uk/2013/11/with-recursive-and-mysql.html?m=1 good intro to WITH

**Comment by romaninsh** [comment]
@tasso85 , thanks for suggesting the feature. I have expanded your definition to be more specific about implementation, in case someone might decide to implement it.

**Comment by DarkSide666** [comment]
This syntax is specific for DB engine, so it should be implemented somewhere in extended engine-specific classes.

**Comment by tasso85** [comment]
It doesn't seem specific to a DB engine to me:

https://www.postgresql.org/docs/9.1/static/queries-with.html
https://msdn.microsoft.com/en-us/library/ms175972.aspx
https://mariadb.com/kb/en/mariadb/with/
http://mysqlserverteam.com/mysql-8-0-labs-recursive-common-table-expressions-in-mysql-ctes/

they all seem to use the same syntax (even though it is still not implemented in MySQL, but is available in MariaDB)

From Wikipedia:

> Common table expressions are supported by Teradata, DB2, Firebird,[14] Microsoft SQL Server, Oracle (with recursion since 11g release 2), PostgreSQL (since 8.4), MariaDB (since 10.2), SQLite (since 3.8.3), HyperSQL and H2 (experimental).[15] Oracle calls CTEs "subquery factoring".[16] Though MySQL does not support common table expressions there exists a demonstration of WITH RECURSIVE emulation[17] using stored procedures.

**Comment by DarkSide666** [comment]
MySQL 8.x now also supports WITH.
