### ISSUE TITLE
Use PDO::quote() to escape values and identifiers

### ISSUE THREAD

**Issue by gartner** [atk4/dsql#127]
I'm new to Agile UI, and was trying to use it on a Postgresql database. Didn't work, as the table name of my models where quoted using backticks. 

Looking into the problem I found that values and identifiers (tablename at least) was often quoted using str_replace() or concatenating them inside backticks. 

Why not use PDO::qoute() for this instead (in \atk4\dsql\Expression) ?

**Comment by DarkSide666** [comment]
Good idea.
Postgresql support currently is not well implemented/tested. It's in near future plans. You can see Oracle support classes for idea how we did that for Oracle DB.

**Comment by romaninsh** [comment]
Gartner, if you create copy of Oracle and specify your class here: https://github.com/atk4/dsql/blob/develop/src/Connection.php#L77.

We would like to do some of that for you this week, and if you can test it on your database, it would be good. We have never used PostgreSQL. :) When you have time, hit our chat room at http://gitter.im/atk4/atk4

**Comment by gartner** [comment]
I'm already on it :-)
The changes made in atk4/dsql after the last release, regarding escaping, is helping a lot in getting it working on postgresql.

**Comment by gartner** [comment]
PDO::quote can only be used to quote values. It is not usefull for identifiers :-(

**Comment by DarkSide666** [comment]
OK. So I guess we don't need it at all then.

**Comment by gartner** [comment]
No no! I still think it would be better to use that, instead of inventing it again. But there would just need to be a method for quoting the identifiers as well. 

I have mainly used Zend Framework, where they have both a quote() and a quoteIdentifier()-method. A similar approach could be used in dsql.

**Comment by romaninsh** [comment]
We only need to escape identifiers. For values we use param(), which substitutes them with ":a" etc.

See http://dsql.readthedocs.io/en/develop/expressions.html?highlight=consume#escaping-methods

So if PDO::quote() is used for values, looks like we don't need it. Close this ticket?
