### ISSUE TITLE
PostgreSQL: Remove id_field value before insert

### ISSUE THREAD

**Issue by gartner** [atk4/dsql#128]
I'm trying to make it work with PostgreSQL. But it gives me some challenges:

I have a table where the id-column is the primary key. It gets its default value from a sequence. (This resembles an auto_increment-column in mysql).

In mysql, you can set an auto_increment columns value to = NULL, and it will take the next value from the auto-increment and use as the content for this column. 

That does not work in PostgreSQL... if you completely omit the column from the INSERT-statement, it will use the default value. Else, it will attempt to use the value you supply for the column in the INSERT-statement.

dsql will always add an 'id'-column with the value NULL when inserting. 

How can this be changed?

**Comment by gartner** [comment]
Found a solution for this. 
In the Model, do this:
```php
    public function init() {
        ....
        $this->addHook('beforeInsert', [$this, 'beforeInsert']);
        ....
    }

    public function beforeInsert($model, &$data) {
        unset($data[$this->id_field]);
        return true;
    }
```
The `&` before `$data` is important. Without it, $data is passed by value, and therefore not changed when returning to the caller.

**Comment by romaninsh** [comment]
This still requires a trigger, right? Is it common to manually pick sequence number and use in insert?

**Comment by romaninsh** [comment]
also i think mysql should also be OK if "id" is unspecified during insert.

**Comment by romaninsh** [comment]
Related: https://github.com/atk4/dsql/pull/126

**Comment by romaninsh** [comment]
Related: https://github.com/atk4/data/issues/280

**Comment by gartner** [comment]
Auto-numbering is done using sequences:
```CREATE TABLE products (
    product_no integer DEFAULT nextval('products_product_no_seq'),
    ...
);```

 but it is used often enough that there is a shorthand for it:

``` 
CREATE TABLE products (
    product_no SERIAL,
    ...
);
```
I never pick the sequence-number manually to use in the insert, and my guess is that it is the most common way to do it. 

However, I think it should be configurable with a flag in the model-class or something, to have the id_field column removed from the INSERT-query.

**Comment by romaninsh** [comment]
https://github.com/atk4/data/pull/284 should address this.

**Comment by mvorisek** [comment]
if you use atk4\data, this has been fully resolved:
https://github.com/atk4/dsql/issues/241
https://github.com/atk4/dsql/pull/243
