### ISSUE TITLE
Passing a \PDO to connect() assumes mysql

### ISSUE THREAD

**Issue by gartner** [atk4/dsql#134]
It is possible to pass a \PDO-instance to Connect::connect() instead of a dsn. 

But when doing so, it is assumed to be a connection to a mysql database.
I have a fix here: https://github.com/gartner/dsql/tree/fix-pdo - but it seems a bit messy. Especially the tests, which although they pass, I am not satisfied with. 
Part of the messy-ness of the tests is that phpunit would not use dataProviders when run on my machine. 

So, now the question is: should I create a pull request, or perhaps instead dsql should _not_ allow a \PDO to be passed to connect() ?

**Comment by romaninsh** [comment]
you should pass it to `new Connection_PostgreSQL($dsn)`.

**Comment by DarkSide666** [comment]
Yes PR would be good, but I think it should work as Romans said above.
If there will be PR, then please also add me as reviewer for it because I have suffered with these PDO issues to while testing with Oracle.
