### ISSUE TITLE
Oracle: DSQL should support LOB type values

### ISSUE THREAD

**Issue by DarkSide666** [atk4/dsql#140]
Currently DSQL doesn't support LOB (BLOB, CLOB) type of values in Expressions.
It always use PDO::PARAM_STR which is limited in size https://github.com/atk4/dsql/blob/develop/src/Expression.php#L561.
Max size may vary depending on database engine, but problems start at about 4k size.

Here is a bit more info https://stackoverflow.com/a/36724762/1466341

Solution - use PARAM_LOB in case string is to long for PARAM_STR. See how Drupal have deal with this issue for Oracle: http://cgit.drupalcode.org/oracle/commit/?id=7590e54, http://cgit.drupalcode.org/oracle/tree/Connection.php?id=7590e549cbd118eedd5afeb989a779e6254bbb66

**Comment by DarkSide666** [comment]
dsql part fix here https://github.com/atk4/dsql/commit/a5b6ee63715a9bb94d502db846d3a02ae0d6ad63

**Comment by mvorisek** [comment]
it seems we need to bind in/out parameter as when I was doing the Oracle CI PR, there was no way to fetch the data instead

check, how DBAL does this, I think this usecase is quite major and should be solved, 👍
