### ISSUE TITLE
Escaping in expressions

### ISSUE THREAD

**Issue by DarkSide666** [atk4/dsql#144]
Maybe we should have some way how to escape `{}` and `[]` parenthesis in expression strings? For example, in standard way - with backslash `\{...\}` and `\[...\]`.

Related question/answer/work-around here: https://stackoverflow.com/a/50759511/1466341

**Comment by romaninsh** [comment]
yes why not

**Comment by mvorisek** [comment]
Valid use case is anything that need the brackets as a string value, like:
```
SELECT val = '[x]';
```
which should be possible to escape like in DQL:
```
SELECT val = '\[x\]';
```

**Comment by mvorisek** [comment]
@DarkSide666 @georgehristov am I correct, that `[]` and/or `{}` is nonsense within string `''` - if yes, we simply ignore the `[]` and `{}` placeholder in it, even no need for backslash :)
