### ISSUE TITLE
Not referring to PDO correctly in PHPDoc

### ISSUE THREAD

**Issue by guym4c** [atk4/dsql#148]
https://github.com/atk4/dsql/blob/b1dd476cbea24f81535621ccd83d4091ca371948/src/Expression.php#L549

Here I think it should be \PDOStatement - I'm happy to open a PR. Just a little sugar to please IDEs!

**Comment by romaninsh** [comment]
oh, i've been updating atk4/ui and atk4/data repositories in the IDEs but haven't gone through dsql at all. So thanks if you spot any other issues like this one, feel free to open PR.

**Comment by DarkSide666** [comment]
Thanks for finding this issue.

All should be fixed now in https://github.com/atk4/dsql/commit/d2c59d89e1762641f05a5b9cd29f875e535dc0f5.

If there are more issues, please let us know by opening new github ticket.
