### ISSUE TITLE
Implement exprNow() method

### ISSUE THREAD

**Issue by DarkSide666** [atk4/dsql#158]
Currently we can do like this in our model:
```
$this->addField('sync_time', [
        'type' => 'datetime',
        'default' => $this->expr('CURRENT_TIMESTAMP'),
]);
```

Issue here is that each DB engine use different syntax for current timestamp:
- MySQL uses `CURRENT_TIMESTAMP()` or `NOW()`
- SQLite uses `CURRENT_TIMESTAMP` (without parenthesis!)
- PgSQL uses `CURRENT_TIMESTAMP` or `NOW()`
- Oracle uses `CURRENT_TIMESTAMP()`
some of them support timezone and some don't and so on.

My proposal is to implement `$persistence->exprNow()` which will rely on `$connection->exprNow()` which in part will create connection driver specific Expression object which should contain exprNow() method something like this:
```
public function exprNow() {
    return $this->expr('CURRENT_TIMESTAMP()');
}
```
This way it will be easy to overwrite in db driver specific expression classes.

**Comment by romaninsh** [comment]
i agree,.. but needs to be consistent with https://github.com/atk4/dsql/blob/develop/src/Query_MySQL.php#L46

**Comment by mvorisek** [comment]
Add parameter `int $precision = 6` to specify precision if the database supports it.
