### ISSUE TITLE
Legal rollback of atomic method

### ISSUE THREAD

**Issue by DarkSide666** [atk4/dsql#160]
### Issue

Sometimes we would like to make _legal_ or _successful_ rollback from `atomic()` method.

Currently it's not possible because:
1. if you call rollback() in atomic callback method, then after method executes Connection->atomic() will try to call commit() and that will fail because transaction is already rolled back.
2. if you throw exception in atomic callback method, then Connection->atomic() will catch it, rollback changes (so far so good), but at the end will throw exception again. So all atomic callback will return exception not successful execution.

### Use-case - simulation mode

```
$db->atomic(function() use ($db, $simulation_mode){
    // do some long running database changes - for example, data import
    // shows results in log file, verifies that all data can be imported etc.
    // ...

    // if in simulation mode then rollback everything
    if ($simulation_mode) {
        $this->app->log('Simulation finished, rolling back');
        $db->rollBack(); // roll back all changes

        // maybe even add some log records in database here - separate transaction
        $db->atomic(function(){ /* ... */ });

        return 'successful_simulation';
    }

    // return status
    return 'successful_import';
});
```

### Possible solutions

**A**. in Connection->atomic() call commit() only if it's in transaction, like this:
```
    public function atomic($f)
    {
        $this->beginTransaction();

        try {
            $res = call_user_func($f);
            if ($this->inTransaction()) { // add this
                $this->commit();
            }

            return $res;
        } catch (\Exception $e) {
            if ($this->inTransaction()) { // add this too just in case there was exception after you have manually rolled back transaction
                $this->rollBack();
            }
            throw $e;
        }
    }
```
Maybe we can even introduce `tryCommit()` and `tryRollBack()` methods and use them here.

**B**. Add special Exception class to throw in this case. Like `class RollbackException`.

```
    public function atomic($f)
    {
        $this->beginTransaction();

        try {
            $res = call_user_func($f);
            $this->commit();

            return $res;
        } catch (\RollbackException $e) { // add this to catch "successful" exceptions
            $this->rollBack();
            return $ret;
        } catch (\Exception $e) {
            $this->rollBack();
            throw $e;
        }
    }
```

**Comment by romaninsh** [comment]
please add as agenda for thursday

**Comment by mvorisek** [comment]
What problem does this solve?

If something fails, the exception should bubble to the top. Why would someone return a success instead of rethrow?

The issue is (I did not lookup in the code) that rollback is not nested?

**Comment by DarkSide666** [comment]
Yes, that's basically it. See my use-case "simulation mode" above.

**Comment by mvorisek** [comment]
@DarkSide666 B is unacceptable - simply throw a custom exception in func and catch it where invoken/app

A - from your code:
```
        try {
            $res = call_user_func($f);
            if ($this->inTransaction()) { // add this
                $this->commit();
            }

            return $res;
        } catch (\Exception $e) {
            if ($this->inTransaction()) { // add this too just in case there was exception after you have manually rolled back transaction
                $this->rollBack();
            }
            throw $e;
        }
```

first added `if` it wrong - if we start a transaction, if MUST be open at the end, if not, it is an error
send added `if` - why? the same reasoning, also, rollback can be normally called more times even if not the nesting level is less/no active transaction

this is core design - do not reinvent wheel, but instead compare top 5 DB frameworks

**Comment by DarkSide666** [comment]
Sorry, I didn't get your point I guess. B looks wrong as "solution", I agree.
But what would be proper solution to my use-case with simulation mode?

Currently problem is this:
_if you call rollback() in atomic callback method, then after method executes Connection->atomic() will try to call commit() and that will fail because transaction is already rolled back._

**Comment by mvorisek** [comment]
DB (at least not every, like MySQL) has no option to simulation mode, thus the only option is to open a different connection and run the simulation you want.

**Comment by DarkSide666** [comment]
Not really. I managed to work around that with solution quite similar to A above in project. Works quite nice while you don't have like 4 nested transactions.

**Comment by mvorisek** [comment]
Simply said, once a query is sent to a DB, then the only way to cancel it is to issue a "ROLLBACK" query which DOES NOT support nesting. Therefore, any simulation must be done inside different/isolated connection.
