### ISSUE TITLE
Segfault in CI tests / GH Actions

### ISSUE THREAD

**Issue by mvorisek** [atk4/dsql#176]
See https://github.com/atk4/dsql/runs/550588314

Issue where it started to be problematic: https://github.com/atk4/dsql/pull/175

![image](https://user-images.githubusercontent.com/2228672/78107898-98be9f80-73f6-11ea-9cab-2f334709d872.png)

It seems that this will be resolved by a new release of Docker images for testing with newer PHP version.

**Comment by romaninsh** [comment]
Does that change and a crash introduces new PHP version requirements?

**Comment by romaninsh** [comment]
I've manually triggered build of atk4/image, it has been upgraded:

```
$ docker pull atk4/image
[..]
$ docker run atk4/image -i  | grep VERS                                                                                       
PHP_VERSION => 7.4.4
$_SERVER['PHP_VERSION'] => 7.4.4
$_ENV['PHP_VERSION'] => 7.4.4
```

Additionally enabling repository link for our base-image (php:..)

<img width="1300" alt="Screenshot 2020-04-13 at 12 16 28" src="https://user-images.githubusercontent.com/453929/79116544-b0940d00-7d80-11ea-8fc2-937569ef06c0.png">
