### ISSUE TITLE
AgileToolKit SSL/TLS

### ISSUE THREAD

**Issue by majictest** [atk4/dsql#192]
HI,

does any body know how to use SSL handshake start connection to mysql using Agiletoolkit datasource:

$db = new \atk4\data\Persistence_SQL(‘mysql:dbname=dbname;host=localhost’, ‘username’, ‘password’);
 We try to solve the issue by using below code:

```
$servername = “localhost”;
$username = “username”;
$password = “password”;
$options = array(
PDO::MYSQL_ATTR_INIT_COMMAND => ‘SET NAMES utf8’,
PDO::MYSQL_ATTR_SSL_CA => ‘server-ca.pem’,
PDO::MYSQL_ATTR_SSL_KEY => ‘client-key.pem’,
PDO::MYSQL_ATTR_SSL_CERT => ‘client-cert.pem’,

PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT => false,
);

try {
$dbcon = new PDO(“mysql:host=$servername;port=3306;dbname=db-name”, $username, $password, $options);
// set the PDO error mode to exception
$dbcon->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
}
catch(PDOException $e)
{
echo "Connection failed: " . $e->getMessage();
}

$conn = new \atk4\dsql\Connection();
$db2 = $conn->connect($dbcon);
$db = new \atk4\data\Persistence_SQL($db2);

```

we come throught different issue unable to search or refresh paging etc... popup message "error “success” : true, “message”:“Success”,“atkjs”"

any suggestion how to do SSL/TLS to do DB connection in agile toolkit?

**Comment by mvorisek** [comment]
as you create PDO directly, the issue is not in atk4
