### ISSUE TITLE
Remove reference property

### ISSUE THREAD

**Issue by mvorisek** [atk4/dsql#200]
Refactor the current code to not use property references as PHP references are very fragile to errors.

See https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/4939

All major repos - core, schema, data, ui are ok expect this repo, the references are set at:
- https://github.com/atk4/dsql/blob/7f6ff3d9c8479f42674488b8bb4b31c86d022d22/src/Expression.php#L282-L283 and unset at:
- https://github.com/atk4/dsql/blob/7f6ff3d9c8479f42674488b8bb4b31c86d022d22/src/Expression.php#L293
- https://github.com/atk4/dsql/blob/7f6ff3d9c8479f42674488b8bb4b31c86d022d22/src/Expression.php#L463

**Comment by mvorisek** [comment]
@georgehristov @DarkSide666 @romaninsh can we address this one/last use of reference properties?

**Comment by DarkSide666** [comment]
Can this be done in BC way?

**Comment by mvorisek** [comment]
I belive yes, it seems this is used for internal rendering only (as far as I remember references are unset before result is returned)
