### ISSUE TITLE
Expression getCastValue turns everything into a string.

### ISSUE THREAD

**Issue by ThatsRicci** [atk4/dsql#234]
I recently updated from 2.0.0 to 2.2.0 and suddenly all of my values coming back from queries are 'strings'.   Originally they worked fine with integer and float data types.  I've traced it to a change in the Expression.php class "getCastValue" function that casts everything to a string.  I believe this should be optional, or at least properly handle other native data types, such as float and integer.   I can't rely on "is_numeric" checks because I need phone numbers and other things to be properly translated as strings when their fields are varchar's. 

I can suggest some changes here, but wondering what the right approach would be: Configurable, vs. adding code to handle the rest of the native types. 

Location: atk4/dsql/src/Expression.php:571

**Comment by mvorisek** [comment]
@ThatsRicci do you use atk4\data? If yes, specify field data type to integer/float, and Model will typecast to integer/float correctly.

If you use dsql directly, please advise your use case.

**Comment by ThatsRicci** [comment]
My use case is dsql directly, in an active-record 'like' setup.   I am not using atk4\data because the mysql schema is legacy and, rather, poorly created so I didn't want to try and recreate all the relationships using a high-level entity/data set framework or ORM.  

It's best I abstract my database for API usage.  This way I can define simple entities for the API to use and API consumers to know about, rather than expose the complex sql schema below. 

That being said my use case is simply like this: 

```
$query = $query->table($this->tableName)
                ->where($field, $value);

            $result = $this->db->getRow($query);
```

The table is basically:
```
create table foo
(
	foo_id int auto_increment,
	name varchar(200) null,
	age int null,
	constraint foo_pk
		primary key (foo_id)
);
```

While on version 2.0.0 and inspecting the $result, and json_encoding($result) the system knows that foo_id and age are numbers so the resulting json is:
```
{
  "foo_id": 1,
  "name": "tony",
  "age": 50
}
```

Now on version 2.2.0 my $result will have all fields converted to a `string` and the resuling json will look like:
```
{
  "foo_id": "1",
  "name": "tony",
  "age": "50"
}
```

This creates issues for our API clients at this time.   Simply detecting numerical values and casting to numbers doesn't work because there are numerical string fields such as:   "code": "1234"   which would be converted to the number 1234, but it's a text field.  I suppose this could be resolved by using atk4/data and properly modeling my schema. 

I forked your repo and resolved it by modifying this function:
\atk4\dsql\Expression::getCastValue

I changed it to this:

```
    /**
     * @param string|int|bool|null $v
     */
    private function getCastValue($v)
    {
        if ($v === null) {
            return null;
        } elseif (is_bool($v)) {
            return $v ? '1' : '0';
        } elseif (is_int($v)) {
            return $v;
        } elseif (is_float($v)){
            return $v;
        } elseif (is_double($v)){
            return $v;
        }

        return (string) $v;
    }
```

this keeps the native types the values are when building the result set. 
The original function in 2.2.0 casted everything to a string, if it wasn't a bool.
```
   /**
     * @param string|int|bool|null $v
     */
    private function getCastValue($v): ?string
    {
        if ($v === null) {
            return null;
        } elseif (is_bool($v)) {
            return $v ? '1' : '0';
        }

        return (string) $v;
    }
```

**Comment by mvorisek** [comment]
@ThatsRicci thanks for the detailed feedback. The current behaviour is correct in sense how we designed it, using native numerical data types was inconsistent across DB vendors. We may look into this once again however, maybe we can get the data type somehow from some metadata.

Forking is one solution to this issue, another may be using https://github.com/cweagans/composer-patches so you receive standard updates without having to update your fork again and again.

**Comment by ThatsRicci** [comment]
Thank you mvorisek! 
I suppose I could override it in `\atk4\dsql\Mysql\Expression` instead to make the patch cleaner and explicitly apply to only mysql data sources.

I will look into composer-patches for my use case moving forward.

**Comment by DarkSide666** [comment]
If I'm not mistaken, then the thing is that in dsql there are no data-types for fields. So there is no way how we can know how to properly cast field value. Only thing what we have are values themselves, but as you said above also string fields like "code" can contain only _string numbers_ and these shouldn't be converted to integer or float.
Solution is to use dsql together with some higher-level ORM, preferably atk4/data or course :)

**Comment by mvorisek** [comment]
I am closing this. The main issue is now that Expression class is extended, ie. it is a base class for Query etc., which is then impossible to further modify/override easily (the best is trait, but it is messy) and I think this is the design issue which should be addressed.

/cc @georgehristov

**Comment by ThatsRicci** [comment]
Thank you team, you may close.  I'm going with a stripped down/lite integration with atk4 DSQL so I won't use a higher-end ORM. I will be fine with my override/patch for the MySql Expression to properly maintain the native sql types into php types.  Reach out to me if it comes up again in any future discussions, I'm happy to lend my perspective!
