### ISSUE TITLE
Liquidate Query->main_table property

### ISSUE THREAD

**Issue by DarkSide666** [atk4/dsql#32]
`Query->main_table` property probably is not needed. At least while we don't have `join` implemented.

Think of it as - SQL query as such doesn't have "default table" so most likely Query class shouldn't have default (main) table also.

**Comment by DarkSide666** [comment]
When we'll get rid of `main_table` property, then I think more changes in `table` can be made.
For example currently DSQL doesn't support multiple tables defined as sub-queries in same query.

**Comment by romaninsh** [comment]
I have commented in chat, but main_table is needed for join() to  function.

**Comment by DarkSide666** [comment]
Well, OK, but I still don't like it :)
