### ISSUE TITLE
table() doesn't save alias when table is defined as Expression

### ISSUE THREAD

**Issue by DarkSide666** [atk4/dsql#33]
Test case:
```
$q = (new Query)->table('employee', 'emp');
$this->assertEquals(
            'select `name` from (select * from `employee` `emp`) `derrived`',
            (new Query)
                ->field('name')
                ->table($q, 'derrived') // <-- this alias is not saved in $args array if table is expression
                ->render()
        );
```
Currently this generates
```
select `name` from (select * from `employee` `emp`)
```
but should be
```
select `name` from (select * from `employee` `emp`) `derrived`
```

**Comment by romaninsh** [comment]
This has been the limitation with original DSQL too. If you FROM another query/expression you can only have one source. 

I am not sure if SQL vendors are happy about having multiple dynamic data sources and joining them together, but if it's a working case, we can implement multi-expression source support through PR.

**Comment by DarkSide666** [comment]
That's why I proposed to always save tables in `$this->args['table'][$table_alias] = $table` structured array.

**Comment by romaninsh** [comment]
I agree, but it's low priority for us. It will not impact the interface either, so we can implement this later.

**Comment by DarkSide666** [comment]
yes it's valid format while you have only one table, but can lead to strange and hard to track SQL issues.

I'm ready to implement this sometime soon, just don't close this issue ;)

**Comment by DarkSide666** [comment]
MySQL will throw exception if we use sub-query as table without alias:
`SQLSTATE[42000]: Syntax error or access violation: 1248 Every derived table must have its own alias`

**Comment by DarkSide666** [comment]
Fixed here: https://github.com/atk4/dsql/pull/64

**Comment by DarkSide666** [comment]
implemented here: https://github.com/atk4/dsql/commit/1a29ef21c57ed1b7b2c1db512639ac2a94f4b13d
