### ISSUE TITLE
if table is defined as Expression (not Query), then it's not wrapped in parenthesis

### ISSUE THREAD

**Issue by DarkSide666** [atk4/dsql#34]
`_consume` wraps only `Query` objects in parenthesis and that's OK.

But in case we use `Expression` object as table it should be wrapped in parenthesis too. See union example in `QueryTest` class.

Now generates:
```
select * from (select * from `sales`) union (select * from `purchases`)
```
should generate:
```
select * from ((select * from `sales`) union (select * from `purchases`)) `derrivedTable`
```
derrivedTable alias will come from fixing https://github.com/atk4/dsql/issues/33

**Comment by DarkSide666** [comment]
On the other hand, we can restrict using `Expression` in `table()` and allow only to use `Query` there.
Then union query will be like this:
```
$u = new Query("[] union []", [$q1, $q2]);
```
instead of
```
$u = new Expression("[] union []", [$q1, $q2]);
```

**Comment by romaninsh** [comment]
this is as per design. If you are defining your own expression, you can specify brackets yourself. Normally expression is used to provide non-escaped code.

Union should use

    new Expression("([] union []) as []", [$q1, $q2, $alias]);

**Comment by DarkSide666** [comment]
I'll close this issue in favor of #33.
