### ISSUE TITLE
Empty string should always be saved as NULL out-of-the-box

### ISSUE THREAD

**Issue by DarkSide666** [atk4/dsql#43]
See: http://forum.agiletoolkit.org/t/save-null-value-to-mysql-db/172/2

I strongly believe that empty string should *never* be saved in DB as such. Empty string is the same as NULL in many DB engines already and have no meaning other than NULL.
So DSQL probably should convert empty string to NULL out-of-the-box.

**Comment by gowrav-vishwakarma** [comment]
No, I don't see this good. Null is null and empty string is empty string. Don't convert. If user wants null he will put null. Or so many count, group and expression may result strange behavior. user must be thinking feed value as empty string and will count it while converting it into null may exclude this by dsql.

**Comment by gowrav-vishwakarma** [comment]
test case : select 1+''; => 1
select 1+null; => null

**Comment by romaninsh** [comment]
+1 gowrav

**Comment by DarkSide666** [comment]
I don't agree with this. Topic can be changed to "empty string values should be converted back to NULL for specific field types" or something like that, but still this is long-time issue. More extended comment of mine here: https://forum.agiletoolkit.org/t/save-null-value-to-mysql-db/172/11?u=imants

**Comment by romaninsh** [comment]
"converting" is outside of the DSQL scope. DSQL should keep things AS-IS.  It's the job of the ORM to cast types ;)

**Comment by romaninsh** [comment]
We have spent some considerable effort to make sure something like this would work:

    $query->set('name', null);
    $query->insert();

**Comment by DarkSide666** [comment]
Ah yes, I forgot that this issue was posted in dsql repo. Should be in atk4 repo :)

**Comment by romaninsh** [comment]
or rather atk4/orm repo

**Comment by DarkSide666** [comment]
maybe orm, but maybe form submit, field value normalization after submit

**Comment by DarkSide666** [comment]
This is how we currently do that for DatePicker field:
https://github.com/atk4/atk4/blob/develop/lib/Form/Field/DatePicker.php#L53
https://github.com/atk4/atk4/blob/develop/lib/Form/Field/DatePicker.php#L67

Something similar should be for numeric fields except that instead of `!$value` there should be `$value===''`
