### ISSUE TITLE
We should properly support tables and fields with spaces e.g. `my table`.

### ISSUE THREAD

**Issue by romaninsh** [atk4/dsql#60]
http://stackoverflow.com/a/23773839/204819
http://stackoverflow.com/questions/18184614/create-a-table-with-a-space-in-the-name-in-mysql
http://stackoverflow.com/questions/506826/selecting-a-database-in-mysql-with-spaces-in-its-name

**Comment by romaninsh** [comment]
#72 now allows us to use funky table names anywhere where we can use expressions. Also field/table aliases now also use hard-escaping.

**Comment by DarkSide666** [comment]
Field names with spaces is not supported everywhere.
For example, in `order()` we explode fieldname by space to separate field name from asc|desc.
https://github.com/atk4/dsql/blob/develop/src/Query.php#L1098

**Comment by romaninsh** [comment]
order supports "array" parameter, in which case we should have a proper handling for spaces in the field name. We probably need to shadow this into _order() for internal implementation and call with extra parameter on which escaping to use.

**Comment by DarkSide666** [comment]
I think this is properly implemented in https://github.com/atk4/dsql/blob/develop/src/Query.php#L1147 and this issue can be closed.
