### ISSUE TITLE
Create test-case for something really complex

### ISSUE THREAD

**Issue by romaninsh** [atk4/dsql#61]
Based on : https://github.com/atk4/dsql/wiki/Awesome-Queries

Create test-cases for complex queries as explained in Wiki.
- [ ] https://github.com/atk4/dsql/wiki/Awesome-Queries#selecting-from-sub-query
- [ ] https://github.com/atk4/dsql/wiki/Awesome-Queries#avoiding-and--or-hell
- [ ] https://github.com/atk4/dsql/wiki/Awesome-Queries#complex-join
- [ ] https://github.com/atk4/dsql/wiki/Awesome-Queries#implementing-if-expressions
- [ ] https://github.com/atk4/dsql/wiki/Awesome-Queries#symfony-query-builder-conditions
- [ ] https://github.com/atk4/dsql/wiki/Awesome-Queries#composing-sub-queries-for-where-in-condition

Old entries (possibly duplicates)
- [ ] http://stackoverflow.com/questions/1925408/handling-complex-where-clauses-with-a-php-query-builder
- [ ] http://stackoverflow.com/questions/33568626/laravel-php-complex-conditional-clause-in-query-builder

**Comment by romaninsh** [comment]
I have added Wiki article:

https://github.com/atk4/dsql/wiki/Awesome-Queries

All of the queries from there should be included in test-suite. I'm updating ticket description.

**Comment by DarkSide666** [comment]
Is this still needed?
