### ISSUE TITLE
implement reset($tag)

### ISSUE THREAD

**Issue by DarkSide666** [atk4/dsql#69]
as described in `queries.rst` document

**Comment by DarkSide666** [comment]
maybe call this method `reset()` because `del()` can be messed with `delete()` easily

**Comment by DarkSide666** [comment]
reset() definitely is better name for this method.

**Comment by romaninsh** [comment]
agree on reset() good call.

**Comment by romaninsh** [comment]
i was worried it might conflict with http://php.net/manual/en/function.reset.php, but looks like we're good.
