### ISSUE TITLE
Execute unbuffered queries

### ISSUE THREAD

**Issue by romaninsh** [atk4/dsql#80]
As described here:

http://php.net/manual/en/mysqlinfo.concepts.buffering.php

It is possible to execute unbuffered queries with PDO. We need to make sure that DSQL can still allow it's user to execute unbuffered queries, where the results are streamed, but this mode should be optional.

We also should look in the situations, when we want to execute query while data are still being fetched. Can PDO properly handle that?

**Comment by mvorisek** [comment]
Closing as pdo result can be used directly with full freedom.
