### ISSUE TITLE
refactor to use Exception from atk4/core 

### ISSUE THREAD

**Issue by romaninsh** [atk4/dsql#88]
because, why keep exceptions in both locations.. ?

**Comment by DarkSide666** [comment]
Then atk4/dsql will have dependency with atk4/core. Currently dsql have no dependecies.

**Comment by romaninsh** [comment]
ok, we can also probably move exception colouring code into some separate class... what do you propose?

**Comment by DarkSide666** [comment]
yeah, atk4/exception :) actually - why not?
I'm not against dsql dependency from core, but in this case I think we can do that without linking dsql and core repos together.

**Comment by romaninsh** [comment]
ok, lets leave as-is.
