### ISSUE TITLE
rolling back nested tranactions

### ISSUE THREAD

**Issue by romaninsh** [atk4/dsql#89]
Question: suppose you have a transaction that adds a new user, that performs multiple operations in DB. This operation calls another routine that adds a new bank account, which also uses a transaction for multiple operations.

Now suppose bank transaction addition operation fails some checks and you want to roll it back. Unfortunately you can't because SQL does not support multiple BEGIN TRANSACTIONS. So the code should somehow throw an exception but I'm not sure how.

**Comment by romaninsh** [comment]
I propose the following solution:

 - when rollback happens inside a deep level , set a flag 
 - once we're to the top-level if rollback is called (which should), clear flag and perform a rollback.
 - otherwise, if the commit is called, rollback anyway and throw an exception, because there is logic in the code.

**Comment by mvorisek** [comment]
Closing as this seems to be solved.
